kind: pipeline
name: debug-test

steps:
  - name: unpack-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./gradle
    volumes:
      - name: cache
        path: /tmp/cache

  - name: build
    image: msfjarvis/docker-android-sdk:latest
    commands:
      - git submodule update --init --recursive
      - ./gradlew assembleDebug lintDebug
    when:
      branch:
        - master

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./gradle
    volumes:
      - name: cache
        path: /tmp/cache
