kind: pipeline
name: debug-test

steps:
  - name: submodules
    image: docker:git
    commands:
      - git submodule update --init --recursive

  - name: build
    image: msfjarvis/docker-android-sdk:latest
    commands:
      - ./gradlew assembleDebug lintDebug

  - name: telegram-deploy
    image: msfjarvis/drone-telegram:local
    settings:
      channel_id: -1001427908832
      artifact_path: app/build/outputs/apk/debug/app-debug.apk
      major_minor: ci
      filename: Viscerion
      bot_token:
        from_secret: bot_token
