kind: pipeline
name: debug-test

steps:
  - name: build
    image: runmymind/docker-android-sdk:ubuntu-standalone
    commands:
      - mkdir -p $ANDROID_HOME/licenses
      - curl "https://download.msfjarvis.website/.viscerion/sdk-licenses.tar.xz" | tar -C "$ANDROID_HOME/licenses/" --strip-components=1 -xvf -
      - git submodule update --init --recursive
      - ./gradlew assemblePieDebug checkPieDebug assembleQuinoaDebug checkQuinoaDebug
    when:
      branch:
        - master
