kind: pipeline
name: debug-test

steps:
  - name: unpack-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./gradle
    volumes:
      - name: cache
        path: /tmp/cache

  - name: build
    image: runmymind/docker-android-sdk:ubuntu-standalone
    commands:
      - mkdir -p $ANDROID_HOME/licenses
      - curl "https://download.msfjarvis.website/.viscerion/sdk-licenses.tar.xz" | tar -C "$ANDROID_HOME/licenses/" --strip-components=1 -xvf -
      - git submodule update --init --recursive
      - ./gradlew assemblePieDebug checkPieDebug assembleQuinoaDebug checkQuinoaDebug
    when:
      branch:
        - master

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./gradle
    volumes:
      - name: cache
        path: /tmp/cache
