kind: pipeline
name: debug-test

steps:
  - name: submodules
    image: docker:git
    commands:
      - git submodule update --init --recursive
    when:
      branch:
        exclude:
          - l10n_master

  - name: build
    image: msfjarvis/docker-android-sdk:latest
    commands:
      - ./gradlew assemblePieDebug assembleQuinoaDebug lintPieDebug lintQuinoaDebug
    when:
      branch:
        exclude:
          - l10n_master

  - name: telegram-deploy-pie
    image: msfjarvis/drone-telegram:local
    settings:
      channel_id: -1001427908832
      artifact_path: ./app/build/outputs/apk/pie/debug/app-pie-debug.apk
      major_minor: pie-ci
      filename: Viscerion
      bot_token:
        from_secret: bot_token
    when:
      branch:
        exclude:
          - l10n_master
      event:
        exclude:
          - pull_request

  - name: telegram-deploy-quinoa
    image: msfjarvis/drone-telegram:local
    settings:
      channel_id: -1001427908832
      artifact_path: ./app/build/outputs/apk/quinoa/debug/app-quinoa-debug.apk
      major_minor: quinoa-ci
      filename: Viscerion
      skip_changelog: true
      bot_token:
        from_secret: bot_token
    when:
      branch:
        exclude:
          - l10n_master
      event:
        exclude:
          - pull_request
