kind: pipeline
name: debug-test

clone:
  disable: true

steps:
  - name: clone
    image: docker:git
    commands:
      - git init
      - git remote add origin git://github.com/MSF-Jarvis/viscerion.git
      - git fetch origin
      - git checkout -f $DRONE_COMMIT
      - git submodule update --init --recursive
    when:
      branch:
        exclude:
          - l10n_master

  - name: export-keys
    image: msfjarvis/drone-decrypt-files:latest
    settings:
      file_to_path_mapping:
        - 'ci/keystore.cipher:keystore.jks|ci/props.cipher:keystore.properties'
      decrypt_key:
        from_secret: key
    when:
      branch:
        exclude:
          - l10n_master
      event:
        exclude:
          - pull_request

  - name: build
    image: msfjarvis/docker-android-sdk:latest
    commands:
      - ./gradlew spotlessCheck :app:assembleDebug :app:lintDebug
    when:
      branch:
        exclude:
          - l10n_master

  - name: telegram-deploy
    image: msfjarvis/drone-telegram:latest
    settings:
      channel_id: -1001278683441
      artifact_path: ./app/build/outputs/apk/debug/app-debug.apk
      major_minor: ci
      filename: Viscerion
      sticker: CAADBAAD8R8AAmSKPgABCOk3mg-Zvf0C
      bot_token:
        from_secret: bot_token
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
