---
kind: pipeline
name: debug-test

platform:
  os: linux
  arch: amd64

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - git fetch --tags
  when:
    branch:
      exclude:
      - l10n_master

- name: export-keys
  image: msfjarvis/drone-decrypt-files:latest
  settings:
    decrypt_key:
      from_secret: key
    file_to_path_mapping:
    - "ci/keystore.cipher:keystore.jks|ci/props.cipher:keystore.properties"
  when:
    branch:
      exclude:
      - l10n_master
    event:
      exclude:
      - pull_request

- name: stylecheck
  image: msfjarvis/docker-android-sdk:ubuntu-standalone
  commands:
  - ./gradlew spotlessCheck
  when:
    branch:
      exclude:
      - l10n_master

- name: build
  image: msfjarvis/docker-android-sdk:ubuntu-standalone
  commands:
  - ./gradlew assembleDebug lintDebug
  when:
    branch:
      exclude:
      - l10n_master

- name: telegram-deploy
  image: msfjarvis/drone-telegram:latest
  settings:
    artifacts: "./app/build/outputs/apk/debug/app-debug.apk:Viscerion"
    bot_token:
      from_secret: bot_token
    channel_id: -1001278683441
    major_minor: ci
    sticker: CAADBAAD8R8AAmSKPgABCOk3mg-Zvf0C
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

...
