name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-testing:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Install coreutils
      run: brew install coreutils

    - name: Checkout repository and submodules
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install go compiler for libwg-go
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.4'

    - name: Clean Cache
      run: rm -rf ~/.gradle/caches

    - uses: actions/cache@v1
      with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/dependencies.gradle') }}

    - name: Download gradle dependencies
      run: ./gradlew dependencies

    - name: Validate codestyle with Spotless
      run: ./gradlew spotlessCheck

    - name: Build app
      run: ./gradlew :app:assembleDebug

    - name: Run unit tests
      run: ./gradlew testDebug
